### ISSUE TITLE
Use standards to format timestamp

### ISSUE THREAD

**Issue by sbocconi** [waagsociety/air_quality_sensor_kit#1]
The format used to describe time (such as ```2019:1:9/17:33:25``` or ```2019:3:4/14:59:32```) is not standard and create problems when parsing the data.

Preferably use a standard such as [rfc3339](https://www.ietf.org/rfc/rfc3339.txt).

**Comment by dgonner** [comment]
In the latest 2.0-7 update the timestamp was changed to standard ISO 8601 format as
described in RFC3339.
A timestamp now looks like `2000-01-01T12:34:56`
